# Generated by Django 4.2.10 on 2026-06-15 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tray_code', models.CharField(max_length=50, unique=True, verbose_name='托盘编号')),
                ('capacity', models.IntegerField(verbose_name='容量上限')),
                ('area', models.CharField(max_length=100, verbose_name='所属区域')),
                ('applicable_sessions', models.CharField(max_length=200, verbose_name='适用场次')),
                ('responsible_person', models.CharField(max_length=50, verbose_name='责任人')),
                ('status', models.CharField(choices=[('pending_pickup', '待领取'), ('checked_out', '已领出'), ('pending_count', '待清点'), ('pending_confirm', '待确认'), ('available', '恢复可用'), ('observing', '观察中')], default='pending_pickup', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '托盘',
                'verbose_name_plural': '托盘',
                'db_table': 'tray',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrayRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=100, verbose_name='适用场次')),
                ('receiver', models.CharField(max_length=50, verbose_name='领取人')),
                ('receive_time', models.DateTimeField(blank=True, null=True, verbose_name='领取时间')),
                ('return_time', models.DateTimeField(blank=True, null=True, verbose_name='归还时间')),
                ('is_returned', models.BooleanField(default=False, verbose_name='是否已归还')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('tray', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='tray.tray', verbose_name='托盘')),
            ],
            options={
                'verbose_name': '领还记录',
                'verbose_name_plural': '领还记录',
                'db_table': 'tray_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_time', models.DateTimeField(auto_now_add=True, verbose_name='清点时间')),
                ('actual_count', models.IntegerField(verbose_name='实际数量')),
                ('expected_count', models.IntegerField(verbose_name='应存数量')),
                ('diff_count', models.IntegerField(verbose_name='差异数量')),
                ('diff_description', models.TextField(blank=True, default='', verbose_name='差异说明')),
                ('confirm_status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认')], default='pending', max_length=20, verbose_name='确认状态')),
                ('confirmer', models.CharField(blank=True, default='', max_length=50, verbose_name='确认人')),
                ('confirm_time', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('conclusion', models.TextField(blank=True, default='', verbose_name='确认结论')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('tray', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='tray.tray', verbose_name='托盘')),
                ('tray_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_records', to='tray.trayrecord', verbose_name='领还记录')),
            ],
            options={
                'verbose_name': '清点记录',
                'verbose_name_plural': '清点记录',
                'db_table': 'inventory_record',
                'ordering': ['-created_at'],
            },
        ),
    ]
