# Generated by Django 4.2.10 on 2026-06-15 02:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tray',
            name='capacity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='容量上限必须大于0')], verbose_name='容量上限'),
        ),
        migrations.CreateModel(
            name='AbnormalHandling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('inventory_diff', '清点差异'), ('observing_status', '观察状态'), ('manual', '人工登记')], default='inventory_diff', max_length=20, verbose_name='异常来源')),
                ('handler', models.CharField(max_length=50, verbose_name='处理责任人')),
                ('measures', models.TextField(blank=True, default='', verbose_name='处理措施')),
                ('expected_completion_time', models.DateTimeField(blank=True, null=True, verbose_name='预计完成时间')),
                ('result', models.TextField(blank=True, default='', verbose_name='处理结果')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('resolved', '已处理'), ('closed', '已关闭')], default='pending', max_length=20, verbose_name='处理状态')),
                ('description', models.TextField(blank=True, default='', verbose_name='异常描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理完成时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('inventory_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abnormal_handlings', to='tray.inventoryrecord', verbose_name='清点记录')),
                ('tray', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abnormal_handlings', to='tray.tray', verbose_name='托盘')),
                ('tray_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abnormal_handlings', to='tray.trayrecord', verbose_name='领还记录')),
            ],
            options={
                'verbose_name': '异常处理单',
                'verbose_name_plural': '异常处理单',
                'db_table': 'abnormal_handling',
                'ordering': ['-created_at'],
            },
        ),
    ]
