# Generated by Django 4.2.10 on 2026-06-15 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0002_alter_tray_capacity_abnormalhandling'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_code', models.CharField(max_length=50, unique=True, verbose_name='任务编号')),
                ('source', models.CharField(choices=[('inventory_diff', '清点差异'), ('observing_tray', '观察中托盘'), ('unclosed_abnormal', '未关闭异常'), ('manual', '人工创建')], default='manual', max_length=20, verbose_name='任务来源')),
                ('status', models.CharField(choices=[('pending_assign', '待指派'), ('processing', '处理中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending_assign', max_length=20, verbose_name='任务状态')),
                ('reviewer', models.CharField(blank=True, default='', max_length=50, verbose_name='复核人')),
                ('review_result', models.CharField(blank=True, choices=[('confirmed_abnormal', '确认异常'), ('false_alarm', '误报'), ('partial_abnormal', '部分异常'), ('other', '其他')], max_length=20, null=True, verbose_name='复核结论')),
                ('review_opinion', models.TextField(blank=True, default='', verbose_name='复核意见')),
                ('review_time', models.DateTimeField(blank=True, null=True, verbose_name='复核时间')),
                ('description', models.TextField(blank=True, default='', verbose_name='任务描述')),
                ('priority', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=10, verbose_name='优先级')),
                ('assign_time', models.DateTimeField(blank=True, null=True, verbose_name='指派时间')),
                ('completed_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('cancelled_time', models.DateTimeField(blank=True, null=True, verbose_name='取消时间')),
                ('cancel_reason', models.TextField(blank=True, default='', verbose_name='取消原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.CharField(blank=True, default='', max_length=50, verbose_name='创建人')),
                ('abnormal_handling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_tasks', to='tray.abnormalhandling', verbose_name='异常处理单')),
                ('inventory_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_tasks', to='tray.inventoryrecord', verbose_name='清点记录')),
                ('tray', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_tasks', to='tray.tray', verbose_name='托盘')),
                ('tray_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_tasks', to='tray.trayrecord', verbose_name='领还记录')),
            ],
            options={
                'verbose_name': '复核任务',
                'verbose_name_plural': '复核任务',
                'db_table': 'review_task',
                'ordering': ['-created_at'],
            },
        ),
    ]
